### ISSUE TITLE
after doing restart, trying to exit causes another restart

### ISSUE THREAD

**Issue by KwisatzJim** [tmiland/invidious-updater#102]
**Describe the bug**
if I do (6) and choose restart, then (10) to exit, it restarts invidious again and remains in the script

**To Reproduce**
1. launch invidious_updater script
2. type 6 and press enter
3. type 3 and press enter
4. type 10 and press enter
5. it instead restarts. and no matter how many times I type 10, it instead restarts. I have to cntrl-c to exit

**Expected behavior**
after doing restart and then trying to exit, it should exit

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.4
 - Browser n/a I use xTerminal Pro to access the Ubuntu box the script runs on

**Additional context**
as a test I just ssh'd into the Ubuntu box from my Macbook Air using iTerm2 and behavior was the same

**Comment by ysarkain** [comment]
I have this issue as well, after I installed invidious, it tried to reinstall every time I told it to exit.

I ran the script again, and restarted invidious, then tried to exit, here is the output:

Select an option [1-10]: 10

      ____          _     ___
     /  _/___ _  __(_)___/ (_)___  __  _______
    / // __ \ | / / / __  / / __ \/ / / / ___/
  _/ // / / / |/ / / /_/ / / /_/ / /_/ (__  )
 /___/_/ /_/|___/_/\__,_/_/\____/\__,_/____/
    __  __          __      __              __
   / / / /___  ____/ /___ _/ /____    _____/ /_
  / / / / __ \/ __  / __ `/ __/ _ \  / ___/ __ \
 / /_/ / /_/ / /_/ / /_/ / /_/  __/ (__  ) / / /
 \____/ .___/\__,_/\__,_/\__/\___(_)____/_/ /_/
     /_/

   This script runs on coffee ☕

    GitHub ➜ https://github.com/sponsors/tmiland
    Coindrop ➜ https://coindrop.to/tmiland

Documentation for this script is available here:
 ➜ https://github.com/tmiland/invidious-updater

➜ Goodbye. ☺

➜ restart Invidious...
✔ done.
● invidious.service - Invidious (An alternative YouTube front-end)
   Loaded: loaded (/etc/systemd/system/invidious.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2023-07-09 23:40:58 UTC; 22ms ago
 Main PID: 4989 (invidious)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/invidious.service
           └─4989 /home/invidious/invidious/invidious -o invidious.log

Jul 09 23:40:58 invidious systemd[1]: Started Invidious (An alternative YouTube front-end).


 ╔═══════════════════════════════════════════════════════════════════╗
 ║                        Invidious Update.sh                        ║
 ║               Automatic update script for Invidious               ║
 ║                      Maintained by @tmiland                       ║
 ║                          version: 2.1.2                           ║
 ╚═══════════════════════════════════════════════════════════════════╝

Welcome to the Invidious Update.sh script.

What do you want to do?

  1) Install Invidious          6) Start, Stop or Restart
  2) Update Invidious           7) Uninstall Invidious
  3) Deploy with Docker         8) Set up PostgreSQL Backup
  4) Add Swap Space             9) Install Nginx
  5) Run Database Maintenance  10) Exit

Services running:
Invidious: ● active PostgreSQL: ● active

Documentation for this script is available here:
 ➜ https://github.com/tmiland/invidious-updater

Select an option [1-10]:
