### ISSUE TITLE
Update failes because of Crystal Version

### ISSUE THREAD

**Issue by lunainvictum** [tmiland/Invidious-Updater#64]
Hey, 

the Update of Invidious failed because the Crystal Version.

I saw that was fixed with 1.5.8.

And now i wanted to try again to update Invidious, but now the Script says Invidious is already up-to-date. But that isnt true.

How can i force to update it? 

And: Why are now Github Credential needed? For what?  

Thanks.

Sry my english is very bad. im native german speaker.

**Comment by tmiland** [comment]
Hi, choose option 6-4 to rebuild. It should at least have done a git pull, even though the build failed.

The fix for Crystal is for new installs only, so you will have to manually downgrade the crystal package.

On Debian: `apt install --reinstall crystal=0.36.1-1`

Update will fail without Credentials.

**Comment by lunainvictum** [comment]
> Hi, choose option 6-4 to rebuild. It should at least have done a git pull, even though the build failed.
> 
> The fix for Crystal is for new installs only, so you will have to manually downgrade the crystal package.
> 
> On Debian: apt install --reinstall crystal=0.36.1-1

Ok.

> Update will fail without Credentials.


But why? Why are now Credentials needed? I dont find anything about it in the last changelogs, or a reason for what this is necessary. 

If i see right, i can stil use 1.5.6. This dont need any Credentials.

**Comment by tmiland** [comment]
> But why? Why are now Credentials needed? I dont find anything about it in the last changelogs, or a reason for what this is necessary.

Because, to be able to git stash and check out a new branch, git asks for credentials, if they aren't provided, the update fails in some cases.

Credentials are stored in `/root/.gitconfig`, and you are only providing what git asks for basically.

Are there any specific reason why you don't want them stored? Then I'll look into a way of doing it differently.

**Comment by tmiland** [comment]
Closing.

Feel free to open again if this is still an issue.
