### ISSUE TITLE
Let's Encrypt fails on freshly-installed Debian 11

### ISSUE THREAD

**Issue by danmanrana** [tmiland/invidious-updater#91]
One line says nginx: command not found. Using the latest version of the script.

**Comment by tmiland** [comment]
What option did you choose?

**Comment by danmanrana** [comment]
Install Nginx -> Install Nginx -> Install or update Nginx-> Stable -> no modules, System's OpenSSL (1.1.1n), then

Install Nginx Vhost for Invidious (unsure if needed but still tested it)
Your Invidious domain name: (doesn't let me input, skips right down)

./invidious_update.sh: line 584: nginx: command not found
Error installing nginx vhost!

Install Let's Encrypt SSL certificates (problematic lines):

[Fri 29 Jul 2022 08:13:44 AM EDT] '-w' is not a valid domain for parameter '-d'
Error issuing Let's Encrypt SSL certificates!
[Fri 29 Jul 2022 08:13:44 AM EDT] '--cert-file' is not a valid domain for parameter '-d'
./invidious_update.sh: line 430: nginx: command not found
Error restarting nginx!

**Comment by tmiland** [comment]
Well, Invidious must be installed and working before using the Nginx option(s).

As for Vagrant, i have no idea.

**Comment by tmiland** [comment]
Not able to reproduce this issue on Debian 11 with latest [Master](https://raw.githubusercontent.com/tmiland/Invidious-Updater/master/invidious_update.sh)

- Step one is to install Invidious with domain and https working.
- Step two, install Nginx (run `nginx -t` after install to make sure it's working)
- Step three, install Nginx Vhost (This will read the domain name from config.yml, which is the domain you set up in step one)

As for the Let's Encrypt SSL cert, I'm not able to test that, since I would need a valid domain to run against,

It was tested by @GauthierPLM - See comment/issue: https://github.com/tmiland/Invidious-Updater/issues/51#issuecomment-778294011

**Comment by GauthierPLM** [comment]
I confirm this is the steps I followed and it worked.
For testing purpose, i didn't setup Invidious in HTTPS Only during install. This allowed me to confirm that Nginx install was working first (so I tested reaching invidious via IP, then via HTTP with Nginx installed, then with HTTPS once the certificate was setup) before going HTTPS only + HSTS.
